### ISSUE TITLE
Request: Google Cloud SDK

### ISSUE THREAD

**Issue by jamesholland-uk** [ajoldham/pantools#1]
Similar to Azure CLi (az), could you include Google Cloud SDK (glcoud)?

These are the steps to install on Ubuntu: (https://cloud.google.com/sdk/docs/downloads-apt-get)

```
apt-get update
apt-get install lsb-release
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
```

Non-interactive might be better though: (https://cloud.google.com/sdk/docs/downloads-versioned-archives)

```
wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-229.0.0-linux-x86_64.tar.gz
tar -xvf google-cloud-sdk-229.0.0-linux-x86_64.tar.gz
./google-cloud-sdk/install.sh -q --path-update true
```

Not fully sure how to integrate this into the Dockerfile to be honest as I'm new to Docker. Thanks!

**Comment by ajoldham** [comment]
Done, thx for the suggestion! :)
